### ISSUE TITLE
Process and import EBMUD Mokelumne training data

### ISSUE THREAD

**Issue by skylerlewis** [FlowWest/swc-habitat-suitability#29]
- [x] Export rasters from HEC-RAS
- [x] Set up ComID boundary polygons
- [x] Set up raster suitability processing
- [x] Run raster suitability processing (rearing and spawning) - don't do the "no baseflow channel removal" version
- [ ] Run statistical model predictions with additional training data
- [ ] Propagate results to prediction dataset, shiny app, etc.

**Comment by MaddeeRubenson** [comment]
@skylerlewis can you please a PR for this and the flow threshold issue?
